version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8091:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - order-service
      - inventory-service

  order-service:
    build: ./order-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/orderdb
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_HOST}:${OTEL_COLLECTOR_PORT_GRPC}
      - INVENTORY_SERVICE_URL=http://inventory-service:8000 
      - OTEL_RESOURCE_ATTRIBUTES=service.name=order-service,service.namespace=demo4
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_PYTHON_LOG_LEVEL=debug
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  inventory-service:
    build: ./inventory-service
    ports:
      - "8002:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventorydb
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_HOST}:${OTEL_COLLECTOR_PORT_GRPC}
      - OTEL_RESOURCE_ATTRIBUTES=service.name=inventory-service,service.namespace=demo4
      - ORDER_SERVICE_URL=http://order-service:8001  # Order service URL
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_PYTHON_LOG_LEVEL=debug
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  invoice-service:
    build:
      context: ./invoice-service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"

volumes:
  postgres_data:
  mongo_data:
